---

- hosts: all
  gather_facts: false
  tasks:
#Intended-Config should be supplied by the user after confirming it works in the development environment.
    - name: Test current Running-Config with supplied Intended-Config
      tags: intended
      cisco.ios.ios_config:
        diff_against: intended
        intended_config: "{{ lookup('file', '~/NetAuto/backup/initial_confs/{{ inventory_hostname }}_IC.cfg') }}"

#config_path should be specified by the user during playbook run.
    - name: Test current Running-Config with Config specified by user (Intended-Config).
      tags: specify
      cisco.ios.ios_config:
        diff_against: intended
        intended_config: "{{ lookup('file', '{{ config_path }}') }}"
