---

- hosts: all
  gather_facts: no
  connection: ansible.netcommon.network_cli
  tasks:

    - name: configure ip address for fa0/2
      cisco.ios.ios_config:
        lines:
          - ip address 192.168.20.2

