---

- hosts: cisco_routers
  gather_facts: false
  tasks:

    - name: Backup configuration
      cisco.ios.ios_config:
        backup: true
        backup_options:
          filename: R1_config_before

    - name: Configure DHCP pools
      vars:
        pools:
          Servers:
            default_router_ip: "10.10.100.1"
            network_id: "10.10.100.0 255.255.255.0"
            parent: "ip dhcp pool Servers"
          OP:
            default_router_ip: "10.10.110.1"
            network_id: "10.10.110.0 255.255.255.0"
            parent: "ip dhcp pool OP"
      cisco.ios.ios_config:
        before: ip dhcp excluded address "{{ item.value.default_router_ip }}"
        lines:
          - network "{{ item.value.network_id }}"
          - default-router "{{ item.value.default_router_ip}}"
          - dns-server 8.8.8.8
        parents: "{{ item.value.parent }}"
      loop: "{{ lookup('dict', pools) }}"


