---

- hosts: cisco_routers
  gather_facts: false
  tasks:

    - name: Backup configuration
      cisco.ios.ios_config:
        backup: true

    - name: Configure DHCP pools
      import_role:
        name: dhcp

    - name: Configure L3_Interfaces
      import_role:
        name: l3_interfaces

    - name: Debug test
      debug:
        var: l3_interfaces_conf
