---

- hosts: all
  gather_facts: false
  vars_prompt:
    - name: ans_us
      prompt: Insert Ansible Username

    - name: ans_pass
      prompt: Insert Ansible Password

  tasks:
    - name: Restoring Configurations to Initial
      tags: initial
      cisco.ios.ios_command:
        commands: 'configure replace scp://{{ ans_us }}:{{ ans_pass }}@10.10.90.16/~/NetAuto/backup/initial_confs/{{ inventory_hostname }}_IC.cfg force'
    
    - name: Restoring Configurations to Specified
      tags: specify
      cisco.ios.ios_command:
        commands: 'configure replace scp://{{ ans_us }}:{{ ans_pass }}@10.10.90.16/{{ config_path }} force'

    - name: Run the Save Configurations Task
      import_role:
        name: save
