---

- hosts: cisco_routers
  gather_facts: false
  pre_tasks:
    - name: Confirmation #Skip this by using --skip-tags always or setting -e skip_confirmation=true
      tags: always
      vars: 
        playbook_name: tagsR1_config_playbook.yml
        skip_confirmation: false
      include_role:
        name: confirmation
      when: skip_confirmation == false

    - name: Backup for Comparison (Before)
      tags: always
      vars:
        skip_compare: false #Skip this by using --skip-tags always or setting -e skip_compare=true
      cisco.ios.ios_config:
        backup: true
        backup_options:
          filename: "{{ inventory_hostname }}_cmp_before.cfg"
          dir_path: backup/compare_confs
      when: skip_compare == false

  tasks:
    - name: Backup configuration
      tags: always
      cisco.ios.ios_config:
        backup: true

    - name: Configure DHCP pools
      tags: dhcp, d_dhcp
      import_role:
        name: dhcp

    - name: Configure L3_Interfaces
      tags: l3_interfaces, d_l3_interfaces
      import_role:
        name: l3_interfaces

  post_tasks:
    - name: Compare with Previous Configuration #Skip this by using --skip-tags always or setting -e skip_compare=true
      tags: always
      vars:
        skip_compare: false
      when: skip_compare == false
      block:
        - name: Backup for Comparison (After)
          cisco.ios.ios_config:
            backup: true
            backup_options:
              filename: "{{ inventory_hostname }}_cmp_after.cfg"
              dir_path: backup/compare_confs
        - name: Compare with Previous Configuration
          cisco.ios.ios_config:
            running_config: "{{ lookup('file', 'backup/compare_confs/{{ inventory_hostname }}_cmp_before.cfg') }}"
            diff_against: intended
            intended_config: "{{ lookup('file', 'backup/compare_confs/{{ inventory_hostname }}_cmp_after.cfg') }}"

    - name: Debug
      tags: never, debug
      block:
        - name: Debug DHCP pools
          tags: debug, d_dhcp
          debug:
            var: dhcp_conf

        - name: Debug L3_Interfaces
          tags: debug, d_l3_interfaces
          debug:
            msg:
              - "{{ l3_interfaces_conf }}"
              - "Interface FastEthernet0/0 has been set to administratively up"
