---

- hosts: cisco_switches
  gather_facts: false
  pre_tasks:
    - name: Confirmation #Skip this by using --skip-tags always or setting -e skip_confirmation=true
      tags: always
      vars:
        playbook_name: tagsSW_config_playbook.yml
        skip_confirmation: false
      include_role:
        name: confirmation
      when: skip_confirmation == false

    - name: Backup for Comparison (Before)
      tags: always
      vars:
        skip_compare: false #Skip this by using --skip-tags always or setting -e skip_compare=true
      cisco.ios.ios_config:
        backup: true
        backup_options:
          filename: "{{ inventory_hostname }}_cmp_before.cfg"
          dir_path: backup/compare_confs
      when: skip_compare == false

  tasks:
    - name: Backup configuration
      tags: always
      cisco.ios.ios_config:
        backup: true

    - name: Configure VLANs
      tags: vlans, d_vlans
      import_role:
        name: vlans #Role has module states configured to merged by default, to override, use -e state_typeA=<statename>

    - name: Configure L2_Interfaces
      tags: l2_interfaces, d_l2_interfaces, tr_d_l2_interfaces, acc_d_l2_interfaces
      import_role: #Role has module states configured to merged by default, to override, use -e state_typeA=<statename>
        name: l2_interfaces

    - name: Configure Management Interfaces
      tags: mgmt_interfaces, d_mgmt_interfaces
      import_role: #Role has module states configured to merged by default, to override, use -e state_typeA=<statename>
        name: mgmt_interfaces

  post_tasks:
    - name: Compare with Previous Configuration #Skip this by using --skip-tags always or setting -e skip_compare=true
      tags: always
      vars:
        skip_compare: false
      when: skip_compare == false
      block:
        - name: Backup for Comparison (After)
          cisco.ios.ios_config:
            backup: true
            backup_options:
              filename: "{{ inventory_hostname }}_cmp_after.cfg"
              dir_path: backup/compare_confs
        - name: Compare with Previous Configuration
          cisco.ios.ios_config:
            running_config: "{{ lookup('file', 'backup/compare_confs/{{ inventory_hostname }}_cmp_before.cfg') }}"
            diff_against: intended
            intended_config: "{{ lookup('file', 'backup/compare_confs/{{ inventory_hostname }}_cmp_after.cfg') }}"

    - name: Debug
      tags: never, debug
      block:
        - name: Debug vlans
          tags: d_vlans
          debug:
            var: vlans_conf

        - name: Debug trunk
          tags: d_l2_interfaces, tr_d_l2_interfaces
          debug:
            var: trunk_conf

        - name: Debug access
          tags: d_l2_interfaces, acc_d_l2_interfaces
          debug:
            var: access_conf

        - name: Debug mgmt
          tags: d_mgmt_interfaces
          debug:
            msg:
              - "{{ mgmt_interfaces_conf }}"
              - "Interface vlan 20 has been set to administratively up"
