---

- hosts: cisco_routers
  gather_facts: false
  pre_tasks:
    - name: Confirmation #Skip this by using --skip-tags always or setting -e skip_confirmation=true
      tags: always
      vars: 
        playbook_name: tagsR1_config_playbook.yml
        skip_confirmation: false
      include_role:
        name: confirmation
      when: skip_confirmation == false

  tasks:

    - name: Backup configuration
      tags: backup
      cisco.ios.ios_config:
        backup: true

    - name: Configure DHCP pools
      tags: dhcp, d_dhcp
      import_role:
        name: dhcp

    - name: Configure L3_Interfaces
      tags: l3_interfaces, d_l3_interfaces
      import_role:
        name: l3_interfaces

    - name: Debug DHCP pools
      tags: debug, d_dhcp
      debug:
        var: dhcp_conf

    - name: Debug L3_Interfaces
      tags: debug, d_l3_interfaces
      debug:
        msg:
          - "{{ l3_interfaces_conf }}"
          - "Interface FastEthernet0/0 has been set to administratively up"
