---
#If you're going to prepend any lines with no, uncomment vars and prepend_info

- hosts: all
  vars:
    prepend_info: Some
  gather_facts: false
  pre_tasks:
    - name: Confirmation #Skip this by using --skip-tags always or setting -e skip_confirmation=true
      tags: always
      vars:
        playbook_name: tagsusers_config_playbook.yml
        skip_confirmation: false
      include_role:
        name: confirmation
      when: skip_confirmation == false

  tasks:
    - name: Configure users
      tags: users, d_users
      cisco.ios.ios_config:
        lines:
          - "{{ item.value.disabled }} {{ item.key }} priv {{ item.value.privilege }} secret {{ item.value.secret }} {{ item.value.hashed_password }}"
      loop: "{{ users | dict2items }}"
      register: users_conf

    - name: Configure SSH keys
      tags: users, d_users
      no_log: false
      cisco.ios.ios_user:
        aggregate:
          - name: "{{ item.key }}"
            sshkey: "{{ item.value.sshkey }}"
            state: "{{ item.value.state }}"  #This will remove the key when set to absent.
      loop: "{{ users | dict2items }}"
      register: ssh_conf

    - name: Debug users
      tags: debug, d_users
      debug:
        var: users_conf

    - name: Debug ssh keys
      tags: debug, d_users
      debug:
        var: ssh_conf
