---

- hosts: cisco_routers
  gather_facts: false
  tasks:

    - name: Backup initial configuration
      cisco.ios.ios_config:
        backup: true
        backup_options:
          filename: R1.backup.cfg
          dir_path: backup/initial_confs

    - name: Restore initial configuration
      cisco.ios.ios_config:
        src: "backup/R1_config_before.j2"
      register: test

    - name: Debug changes
      debug:
        var: test
