---

- hosts: cisco_routers
  gather_facts: false
  tasks:

    - name: Run commands that require answering a prompt
      cisco.ios.ios_command:
       commands:
        - command: "clear counters FastEthernet0/1"
          prompt: 'Clear "show interface" counters on this interface \[confirm\]'
        - command: "clear counters Ethernet1/0"
          prompt: "[confirm]"
      register: result

    - name: debug
      debug:
        var: result
