---
#If you're going to prepend any lines with no, uncomment vars and prepend_info

- hosts: all
  #vars:
    #prepend_info: Some
  gather_facts: false
  pre_tasks:
    - name: Run the Confirmation Task #Skip this by using --skip-tags always or setting -e skip_confirmation=true
      vars: #This var determines which role will be included by the task.
        role_name: users_confirmation
      import_tasks:
        file: tasks/confirmation_task.yml

    - name: Run the Backup for Comparison (Before) Task #Skip this by using --skip-tags always or setting -e skip_compare=true
      import_tasks:
        file: tasks/compare_before_task.yml

    - name: Backup configuration
      tags: always
      cisco.ios.ios_config:
        backup: true

  tasks:
    - name: Configure users
      tags: users, d_users
      cisco.ios.ios_config:
        lines:
          - "{{ item.value.disabled }} {{ item.key }} priv {{ item.value.privilege }} secret {{ item.value.secret }} {{ item.value.hashed_password }}"
      loop: "{{ users | dict2items }}"
      register: users_conf

    - name: Configure SSH keys
      tags: users, d_users
      no_log: false
      cisco.ios.ios_user:
        aggregate:
          - name: "{{ item.key }}"
            sshkey: "{{ item.value.sshkey }}"
            state: "{{ item.value.state }}"  #This will remove the key when set to absent.
      loop: "{{ users | dict2items }}"
      register: ssh_conf

  post_tasks:
    - name: Run the Compare with Previous Configuration Task #Skip this by using --skip-tags always or setting -e skip_compare=true
      import_tasks:
        file: tasks/compare_after_task.yml

    - name: Debug
      tags: never, debug
      block:
        - name: Debug users
          tags: debug, d_users
          debug:
            var: users_conf

        - name: Debug ssh keys
          tags: debug, d_users
          debug:
            var: ssh_conf

    - name: Save
      tags: never, save
      import_tasks:
        file: tasks/save_task.yml
