- name: Compare with Previous Configuration
  block:
    - name: Backup for Comparison (After)
      cisco.ios.ios_config:
        backup: true
        backup_options:
          filename: "{{ inventory_hostname }}_cmp_after.cfg"
          dir_path: backup/compare_confs
    - name: Compare with Previous Configuration
      cisco.ios.ios_config:
        running_config: "{{ lookup('file', 'backup/compare_confs/{{ inventory_hostname }}_cmp_before.cfg') }}"
        diff_against: intended
        intended_config: "{{ lookup('file', 'backup/compare_confs/{{ inventory_hostname }}_cmp_after.cfg') }}"
