#If you're going to prepend any lines with no, uncomment vars and prepend_info

- name: Configure DHCP pools
  #vars:
    #prepend_info: Some
  cisco.ios.ios_config:
    before: "ip dhcp excluded-address {{ item.value.excluded_address }}"
    lines:
      - "network {{ item.value.network_id }}"
      - "default-router {{ item.value.default_router_ip }}"
      - dns-server 8.8.4.4
    parents: "ip dhcp pool {{ item.key }}"
  loop: "{{ pools | dict2items }}"
  register: dhcp_conf
