- name: Configure DHCP pools
  cisco.ios.ios_config:
    before: "ip dhcp excluded address {{ item.value.excluded_address }}"
    lines:
      - "network {{ item.value.network_id }}"
      - "default-router {{ item.value.default_router_ip }}"
      - dns-server 8.8.8.8
    parents: "ip dhcp pool {{ item.key }}"
  loop: "{{ pools | dict2items }}"
  register: dhcp_conf
