vlans:
  VLAN10_Servers:
    name: Servers
    vlan_id: 10
  VLAN20_IT:
    name: IT
    vlan_id: 20

l2_interfaces:
  Ethernet0/0:
    mode: trunk
    allowed_vlans: 10,20
  range Ethernet0/1-3:
    mode: access
    vlan: 10
  range Ethernet1/0-3:
    mode: access
    vlan: 10

mgmt_ip_address: "10.10.90.204 255.255.255.0"
