vlans:
  VLAN20_IT:
    name: IT
    vlan_id: 20
    state_typeA: merged
  VLAN30_OP:
    name: OP
    vlan_id: 30
    state_typeA: "{{ state_typeA_global }}"

l2_interfaces:
  Ethernet0/0:
    mode: trunk
    allowed_vlans: 30,20
    state_typeA: merged
  range Ethernet0/1-3:
    mode: access
    vlan: 30
    state_typeA: "{{ state_typeA_global }}"
  range Ethernet1/0-3:
    mode: access
    vlan: 30
    state_typeA: "{{ state_typeA_global }}"


mgmt_ip_address: "10.10.90.205 255.255.255.0"
