vlans:
  VLAN10_Servers:
    name: Servers
    vlan_id: 10
  VLAN20_IT:
    name: IT
    vlan_id: 20
  VLAN30_IT:
    name: OP
    vlan_id: 30

l2_interfaces:
  range Ethernet0/0-1:
    mode: trunk
    allowed_vlans: 1-300

mgmt_ip_address: "10.10.90.201 255.255.255.0"
