vlans:
  VLAN10_Servers:
    name: Servers
    vlan_id: 10
  VLAN20_IT:
    name: IT
    vlan_id: 20
  VLAN30_IT:
    name: OP
    vlan_id: 30

l2_interfaces:
  Ethernet0/0:
    mode: trunk
    allowed_vlans: 1-300
  Ethernet0/1:
    mode: access
    vlan: 20
  Ethernet0/2:
    mode: trunk
    allowed_vlans: 10,20
  Ethernet0/3:
    mode: trunk
    allowed_vlans: 30,20

mgmt_ip_address: "10.10.90.202 255.255.255.0"
