---

- name: L3 Interface Configuration
  hosts: cisco_routers
  gather_facts: false
  tasks:

    - name: Backup current running configuration
      cisco.ios.ios_config:
        backup: true

    - name: Collect CLI configuration for L3 F0/1 Interface
      cisco.ios.ios_l3_interfaces:
        config:
          - name: fa0/1
            ipv4:
              - address: 192.168.20.1/24
        state: rendered
      register: conf

    - name: View rendered facts
      debug:
        var: conf
